spring.application.name=hibernatedemo-app

spring.datasource.url=jdbc:postgresql://localhost:5432/hibernate_db
spring.datasource.username=postgres
spring.datasource.password=Temp@123456
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate / JPA settings
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.error.include-stacktrace=never
server.error.include-message=always

spring.devtools.restart.enabled=true


logging.file.name=logs/account-management-service.log
logging.level.root=INFO
logging.file.max-size=10MB
logging.file.max-history=30
logging.file.total-size-cap=250MB
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger - %msg%n

